In [11]:
import numpy as np

X = np.arange(1,5,1)
Y = np.arange(0,3,1)

Xarr,Yarr = np.meshgrid(X,Y)
mesh = Xarr*Yarr
print(Xarr, '\n \n',  Yarr,'\n')
print(mesh)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]] 
 
 [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]] 

[[0 0 0 0]
 [1 2 3 4]
 [2 4 6 8]]


In [ ]:
import matplotlib.pyplot as plt

